package com.adolf.zhouzhuang;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.adolf.zhouzhuang.Spots;
import com.adolf.zhouzhuang.Favorites;

import com.adolf.zhouzhuang.SpotsDao;
import com.adolf.zhouzhuang.FavoritesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig spotsDaoConfig;
    private final DaoConfig favoritesDaoConfig;

    private final SpotsDao spotsDao;
    private final FavoritesDao favoritesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        spotsDaoConfig = daoConfigMap.get(SpotsDao.class).clone();
        spotsDaoConfig.initIdentityScope(type);

        favoritesDaoConfig = daoConfigMap.get(FavoritesDao.class).clone();
        favoritesDaoConfig.initIdentityScope(type);

        spotsDao = new SpotsDao(spotsDaoConfig, this);
        favoritesDao = new FavoritesDao(favoritesDaoConfig, this);

        registerDao(Spots.class, spotsDao);
        registerDao(Favorites.class, favoritesDao);
    }
    
    public void clear() {
        spotsDaoConfig.getIdentityScope().clear();
        favoritesDaoConfig.getIdentityScope().clear();
    }

    public SpotsDao getSpotsDao() {
        return spotsDao;
    }

    public FavoritesDao getFavoritesDao() {
        return favoritesDao;
    }

}
