package com.adolf.zhouzhuang;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.adolf.zhouzhuang.Spots;

import com.adolf.zhouzhuang.SpotsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig spotsDaoConfig;

    private final SpotsDao spotsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        spotsDaoConfig = daoConfigMap.get(SpotsDao.class).clone();
        spotsDaoConfig.initIdentityScope(type);

        spotsDao = new SpotsDao(spotsDaoConfig, this);

        registerDao(Spots.class, spotsDao);
    }
    
    public void clear() {
        spotsDaoConfig.getIdentityScope().clear();
    }

    public SpotsDao getSpotsDao() {
        return spotsDao;
    }

}
