package com.adolf.zhouzhuang;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "spots".
 */
public class Spots {

    private Long id;
    private int pid;
    private Integer order;
    private Long createTime;
    private String title;
    private String brief;
    private String detailUrl;
    private String lat;
    private String lng;
    private String videoLocation;
    private Integer videoVersion;
    private Integer basicInfoVersion;

    public Spots() {
    }

    public Spots(Long id) {
        this.id = id;
    }

    public Spots(Long id, int pid, Integer order, Long createTime, String title, String brief, String detailUrl, String lat, String lng, String videoLocation, Integer videoVersion, Integer basicInfoVersion) {
        this.id = id;
        this.pid = pid;
        this.order = order;
        this.createTime = createTime;
        this.title = title;
        this.brief = brief;
        this.detailUrl = detailUrl;
        this.lat = lat;
        this.lng = lng;
        this.videoLocation = videoLocation;
        this.videoVersion = videoVersion;
        this.basicInfoVersion = basicInfoVersion;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getPid() {
        return pid;
    }

    public void setPid(int pid) {
        this.pid = pid;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBrief() {
        return brief;
    }

    public void setBrief(String brief) {
        this.brief = brief;
    }

    public String getDetailUrl() {
        return detailUrl;
    }

    public void setDetailUrl(String detailUrl) {
        this.detailUrl = detailUrl;
    }

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getLng() {
        return lng;
    }

    public void setLng(String lng) {
        this.lng = lng;
    }

    public String getVideoLocation() {
        return videoLocation;
    }

    public void setVideoLocation(String videoLocation) {
        this.videoLocation = videoLocation;
    }

    public Integer getVideoVersion() {
        return videoVersion;
    }

    public void setVideoVersion(Integer videoVersion) {
        this.videoVersion = videoVersion;
    }

    public Integer getBasicInfoVersion() {
        return basicInfoVersion;
    }

    public void setBasicInfoVersion(Integer basicInfoVersion) {
        this.basicInfoVersion = basicInfoVersion;
    }

}
